# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 17:42
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('is_public', models.BooleanField(default=True, help_text='Public photographs will be displayed in the default views.', verbose_name='Is photo public')),
                ('photo', models.ImageField(upload_to=core.models.save_image, verbose_name='Image')),
                ('store_link', models.URLField(blank=True, null=True, verbose_name='Store link')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
